version: '3.8'

services:
  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password!@#
      MYSQL_USER: yeomc
      MYSQL_PASSWORD: password!@#
    container_name: mariadb-11
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - '3307:3306'
    volumes:
      - ./data/mariadb:/var/lib/mysql
