version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: yeomc
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yeomc
    container_name: postgres-14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres-14-alpine:/var/lib/postgresql/data
