version: '3.8'

services:
  postgres:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: yeomc
      POSTGRES_PASSWORD: password!@#
    container_name: postgres-16.0
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
