version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis-latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
